"""Evidence tags and severities — authoritative mapping is RULES.md §13."""

from __future__ import annotations

from typing import Literal

Decision = Literal["APPROVE", "HOLD", "ESCALATE"]
Severity = Literal["HOLD", "ESCALATE"]

# §13 tag list
INVOICE_INCOMPLETE = "INVOICE_INCOMPLETE"
PO_NOT_FOUND = "PO_NOT_FOUND"
RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND"
VENDOR_RECORD_NOT_FOUND = "VENDOR_RECORD_NOT_FOUND"
VENDOR_MISMATCH = "VENDOR_MISMATCH"
CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
LINE_NOT_MATCHED = "LINE_NOT_MATCHED"
ARITHMETIC_MISMATCH = "ARITHMETIC_MISMATCH"
QUANTITY_TOLERANCE_EXCEEDED = "QUANTITY_TOLERANCE_EXCEEDED"
PRICE_TOLERANCE_EXCEEDED = "PRICE_TOLERANCE_EXCEEDED"
VENDOR_AP_HOLD = "VENDOR_AP_HOLD"
STANDARD_APPROVAL_MISSING_OR_INVALID = "STANDARD_APPROVAL_MISSING_OR_INVALID"
PO_CONFLICT_UNRESOLVED = "PO_CONFLICT_UNRESOLVED"
VENDOR_SUSPENDED = "VENDOR_SUSPENDED"
OUTSIDE_DELEGATION = "OUTSIDE_DELEGATION"

ALL_TAGS: frozenset[str] = frozenset(
    {
        INVOICE_INCOMPLETE,
        PO_NOT_FOUND,
        RECEIPT_NOT_FOUND,
        VENDOR_RECORD_NOT_FOUND,
        VENDOR_MISMATCH,
        CURRENCY_MISMATCH,
        LINE_NOT_MATCHED,
        ARITHMETIC_MISMATCH,
        QUANTITY_TOLERANCE_EXCEEDED,
        PRICE_TOLERANCE_EXCEEDED,
        VENDOR_AP_HOLD,
        STANDARD_APPROVAL_MISSING_OR_INVALID,
        PO_CONFLICT_UNRESOLVED,
        VENDOR_SUSPENDED,
        OUTSIDE_DELEGATION,
    }
)

# Derived subset for validator/generator hints only 
BLOCKING_TAGS: frozenset[str] = frozenset(
    {
        INVOICE_INCOMPLETE,
        PO_NOT_FOUND,
        RECEIPT_NOT_FOUND,
        VENDOR_RECORD_NOT_FOUND,
        LINE_NOT_MATCHED,
        PO_CONFLICT_UNRESOLVED,
    }
)

TAG_SEVERITY: dict[str, Severity] = {
    INVOICE_INCOMPLETE: "HOLD",
    PO_NOT_FOUND: "HOLD",
    RECEIPT_NOT_FOUND: "HOLD",
    VENDOR_RECORD_NOT_FOUND: "HOLD",
    VENDOR_MISMATCH: "HOLD",
    CURRENCY_MISMATCH: "HOLD",
    LINE_NOT_MATCHED: "HOLD",
    ARITHMETIC_MISMATCH: "HOLD",
    QUANTITY_TOLERANCE_EXCEEDED: "HOLD",
    PRICE_TOLERANCE_EXCEEDED: "HOLD",
    VENDOR_AP_HOLD: "HOLD",
    STANDARD_APPROVAL_MISSING_OR_INVALID: "HOLD",
    PO_CONFLICT_UNRESOLVED: "ESCALATE",
    VENDOR_SUSPENDED: "ESCALATE",
    OUTSIDE_DELEGATION: "ESCALATE",
}
